version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    volumes:
      - ./app/media:/app/app/media # persist media
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/media:/app/app/media
    depends_on:
      - fastapi
    restart: always

volumes:
  postgres_data:
