version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    volumes:
      - ./app/media:/app/app/media # persist media
    command: >
      sh -c "cd app && alembic upgrade head && gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --access-logfile -"
    depends_on:
      - db
    restart: always
    env_file:
    - app/.env   # ✅ ADD THIS LINE

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/media:/app/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fastapi
    restart: always

volumes:
  postgres_data:
