"""removed visible

Revision ID: c1ce82a59d32
Revises: 20c2d028cf6a
Create Date: 2025-05-13 11:55:01.874841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ce82a59d32'
down_revision: Union[str, None] = '20c2d028cf6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'visible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
